### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [TommerHaugland/prj-rev-bwfs-dasmoto#3]
Overall met expectations.

In this first project I look at two main criteria with the goal to correct these issues now so they do not appear later as the projects increase in complexity.

Is the html organized and manage well using divs and classes/ids.

Great on this, you had each section in a div which is exactly what I look for.

Second is the css efficient and not overly repetitive.

Overall you were good on this, the font family being repeated is one of the more common mistakes in the first submission.

Nice use of jquery here, you are only the second review I have seen on this first project to try to use it.  Even though it is just a console.log a lot of learners are afraid to even take this step.

To prepare you for upcoming projects, go to flexboxfroggy.com, see how far you can get. The later projects use flexbox heavily.

**Comment by TommerHaugland** [comment]
Thanks for the feedback, Farish!
